name: 'Check Branch'

on:
  pull_request:

permissions:
  contents: read

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'dev'
        run: |
          echo "ERROR: You can only merge into main from dev branch"
          exit 1
